[package]
authors = ["Daniel Egger <daniel@eggers-club.de>"]
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]
description = "Peripheral access API for STM32F042 microcontrollers"
documentation = "https://docs.rs/stm32f042-hal"
keywords = [
    "arm",
    "cortex-m",
    "stm32f042",
    "hal",
]
license = "0BSD"
name = "stm32f042-hal"
repository = "https://github.com/therealprof/stm32f042-hal"
version = "0.3.3"

[dependencies]
bare-metal = "0.1.1"
cortex-m = "0.4.3"
nb = "0.1.1"
numtoa = "0.0.7"

[dependencies.cast]
default-features = false
version = "0.2.2"

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.1.2"

[dependencies.stm32f042]
features = ["rt"]
version = "0.5.1"

[features]
default = ["rt"]
rt = []
[profile.dev]
debug = true
lto = true

[profile.release]
debug = true
lto = true
opt-level = "s"
